cuda_tile.module @matmul {
  // Computes C = A * B for row-major 256x256 matrices using a 16x16x1 grid.
  // Each program computes one 16x16 output tile.

  // You can convert your program using
  // `cuda-tile-translate matmul.mlir --mlir-to-cudatilebc > bytecode.bc` then
  // pass the generated bytecode to
  // `python run_matmul.py bytecode.bc --grid 16 16 1`.

  // If you are missing operations, check out `matmul-cheat-sheet.md`.

  entry @matmul_256x256x256(
      %a: tile<ptr<f16>>,
      %b: tile<ptr<f16>>,
      %c: tile<ptr<f32>>) {
    // First, convert the pointers into tensor views.
    // This will provide information to the compiler about the shape
    // of the underlying tensor.
    // In out example, the tensors are all 256x256 in column-major
    // striding (stride [256, 1]).

    // ...

    // Then, create partition views out of the tensor views.
    // This will specify to the compiler how the underlying tensors
    // must be partitioned. Here, we want to operate on tiles
    // of shape 16x16, so the partition must be over 16x16 tiles.

    // ...

    // Then, we perform the main loop over the tile column and
    // tile row to consider in the covered tile.
    // Do not forget to define the values used for bounding the
    // for loop and initializing the accumulator!
    %result = for %k in (%c0 to %k_dim_size, step %c1) : tile<i32>
        iter_values(%acc = %zero) -> (tile<16x16xf32>) {
      // We first need to load the tile from A.
      // Which tile to load depends on the current tile program ID!
      // Make sure you are computing the right tile of C based on this.

      // ...

      // Then the tile from B.

      // ...

      // Then do the multiplication.

      // ...

      // Finally, set the accumulator to the newly multiplied value.
      
      // ...
    }

    // Once the tile is fully computed, store it to the right location in C.

    // ...
  }
}
