cuda_tile.module @matmul {
  // Computes C = A * B for row-major 256x256 matrices using a 16x16x1 grid.
  // Each program computes one 16x16 output tile.

  // You can convert your program using
  // `cuda-tile-translate matmul.mlir --mlir-to-cudatilebc > bytecode.bc` then
  // pass the generated bytecode to
  // `python run_matmul.py bytecode.bc --grid 16 16 1`.

  // If you are missing operations, check out `matmul-cheat-sheet.md`.

  entry @matmul_256x256x256(
      %a: tile<ptr<f16>>,
      %b: tile<ptr<f16>>,
      %c: tile<ptr<f32>>) {
    // First, convert the pointers into tensor views.
    // This will provide information to the compiler about the shape
    // of the underlying tensor.
    // In out example, the tensors are all 256x256 in column-major
    // striding (stride [256, 1]).
    %a_tensor = make_tensor_view %a,
        shape = [256, 256], strides = [256, 1]
        : tensor_view<256x256xf16, strides=[256,1]>
    %b_tensor = make_tensor_view %b,
        shape = [256, 256], strides = [256, 1]
        : tensor_view<256x256xf16, strides=[256,1]>
    %c_tensor = make_tensor_view %c,
        shape = [256, 256], strides = [256, 1]
        : tensor_view<256x256xf32, strides=[256,1]>

    // Then, create partition views out of the tensor views.
    // This will specify to the compiler how the underlying tensors
    // must be partitioned. Here, we want to operate on tiles
    // of shape 16x16, so the partition must be over 16x16 tiles.
    %a_view = make_partition_view %a_tensor
        : partition_view<tile=(16x16), tensor_view<256x256xf16, strides=[256,1]>>
    %b_view = make_partition_view %b_tensor
        : partition_view<tile=(16x16), tensor_view<256x256xf16, strides=[256,1]>>
    %c_view = make_partition_view %c_tensor
        : partition_view<tile=(16x16), tensor_view<256x256xf32, strides=[256,1]>>

    %pid_m, %pid_n, %pid_z = get_tile_block_id : tile<i32>
    %m_dim_size, %k_dim_size = get_index_space_shape %a_view
        : partition_view<tile=(16x16), tensor_view<256x256xf16, strides=[256,1]>>
          -> tile<i32>
    %c0 = constant <i32: 0> : tile<i32>
    %c1 = constant <i32: 1> : tile<i32>
    %zero = constant <f32: 0.0> : tile<16x16xf32>

    // Then, we perform the main loop over the tile column and
    // tile row to consider in the covered tile.
    // Do not forget to define the values used for bounding the
    // for loop!
    %result = for %k in (%c0 to %k_dim_size, step %c1) : tile<i32>
        iter_values(%acc = %zero) -> (tile<16x16xf32>) {
      // We first need to load the tile from A.
      // Which tile to load depends on the current tile program ID!
      // Make sure you are computing the right tile of C based on this.
      %a_tile, %a_token = load_view_tko weak %a_view[%pid_m, %k]
          : partition_view<tile=(16x16), tensor_view<256x256xf16, strides=[256,1]>>,
            tile<i32> -> tile<16x16xf16>, token

      // Then the tile from B.
      %b_tile, %b_token = load_view_tko weak %b_view[%k, %pid_n]
          : partition_view<tile=(16x16), tensor_view<256x256xf16, strides=[256,1]>>,
            tile<i32> -> tile<16x16xf16>, token

      // Then do the multiplication.
      %next = mmaf %a_tile, %b_tile, %acc
          : tile<16x16xf16>, tile<16x16xf16>, tile<16x16xf32>
    
      // Finally, set the accumulator to the newly multiplied value.
      continue %next : tile<16x16xf32>
    }

    // Once the tile is fully computed, store it to the right location in C.
    %store_token = store_view_tko weak %result,
        %c_view[%pid_m, %pid_n]
        : tile<16x16xf32>,
          partition_view<tile=(16x16), tensor_view<256x256xf32, strides=[256,1]>>,
          tile<i32> -> token
  }
}
